train_cdr_config:
  task_name: "CDR"
  data_dir: dataset/cdr
  train_file: train_filter.data
  dev_file: dev_filter.data
  test_file: test_filter.data
  max_seq_length: 1024
  train_batch_size: 4
  test_batch_size: 8
  gradient_accumulation_steps: 1
  num_labels: 2
  learning_rate: 2e-5
  adam_epsilon: 1e-6
  weight_decay: 1e-5
  max_grad_norm: 1.0
  warmup_ratio: 0.06
  num_train_epochs: 30