train_cdr_config:
  encoder_config:
    model_name: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext 
  
  gnn_config:
    num_layer: 2  
    node_type_embedding: 50

  augmentation_config:
    tau: 0.7

  learning_rate: 0.00002
  
